openapi: 3.0.0
info:
  title: Canis Major Validation Service
  version: 1.0.0
  description: API for validating entities between Orion and Blockchain responses.
  contact:
    email:asma.taamallah@fiware.org
paths:
  /validation/entity/{entityId}/transactions
  get:
    summary: Retrieve entity transactions
    operationId: getEntityTransactions
    tags:
      - Validation
    parameters:
      - name: entityId
      in: path
      required: true
      description: The ID of the entity to retrieve transactions for
      schema:
        type: string
    responses:
      '200':
        description: Successful retrieval of entity transactions
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/EntityTransactionList'
      '404':
        description: Entity not found
      '500':
        description: Internal server error
  /validation/entity/{entityId}/validate:
    post:
      summary: Validate an entity
      operationId: validateEntity
      tags:
        - Validation
      parameters:
       - name: entityId
        in: path
        required: true
        description: The ID of the entity to validate
        schema:
          type: string
      requestBody:
        required: true 
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/ValidationRequest'
      responses:
        '200':
          description: Validation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
        '400':
          description: Bad request
        '404':
          description: Entity not found
        '500':
        description: Internal server error
components:
  schemas:
    EntityTransactionList:
      type: object
      properties:
        transactions:
          type: array
          items: 
             $ref: '#/components/schemas/EntityTransaction'
    EntityTransaction:
      type: object
      properties:
        id: 
          type: string
          format: uri
        status:
          type: string
        blockNumber:
          type: integer
        transactionHash:
          type: string
        from:
          type: string
        to:
          type: string
    ValidationRequest:
      type: object
      properties:
        additionalData:
          type: string
    ValidationResult:
      type: object
      properties:
        valid:
          type: boolean
        errors:
          type: array
          items:
            type: string

