ngsi:
  contextBrokerUrl: "127.0.0.1:1026" # Replace with your context broker URL
  canisMajorUrl: "127.0.0.1:4000" # Replace with your Canis Major URL
  NGSILD_TENANT: "orion" # Replace with your tenant ID