version: "3.5"
services:

  # Hashicorp vault as a wallet
  vault-server:
    image: ${VAULT_IMAGE:-quay.io/fiware/vault-ethereum:1.0.1}
    hostname: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK
    networks:
      - test-network

  # Fiware environment setup
  orion-ld:
    image: ${ORION_IMAGE:-quay.io/fiware/orion-ld:1.7.1}
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - test-network
    ports:
      - ${EXPOSED_PORT:-1026}:${ORION_LD_PORT:-1026} # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG -forwarding -mongocOnly
    healthcheck:
      test: curl --fail -s http://orion:${ORION_LD_PORT}/version || exit 1
      interval: 30s

  mongo-db:
    image: ${MONGO_DB_VERSION:-mongo:6.0}
    hostname: mongo-db
    container_name: db-mongo
    ports:
      - "${MONGO_DB_PORT:-27017}:${MONGO_DB_PORT:-27017}" # localhost:27017
    networks:
      - test-network
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb
    healthcheck:
      test: ["CMD","mongosh", "localhost:27017/test", "--quiet"]
      interval: 30s

  # aei and eth
  aei-contract:
    image: quay.io/wi_stefan/py-contract:latest
    hostname: aei-contract
    networks:
      - test-network
    environment:
      - RPC_ENDPOINT=ganache-cli
      - RPC_PORT=8545
    depends_on:
      - ganache-cli

  ganache-cli:
    image: trufflesuite/ganache-cli:latest
    hostname: ganache-cli
    networks:
      - test-network
    ports:
      - "8545:8545"
    command: ganache-cli -l 8000000 --gasPrice 0 --account '0x22aabb811efca4e6f4748bd18a46b502fa85549df9fa07da649c0a148d7d5530, 100000000000000000000'

#volumes:
#  contract-folder: ~

volumes:
  mongo-db: ~
  mongo-config: ~

networks:
  test-network:
    driver: bridge