version: "3.5"
services:
  ## CanisMajor setup

  canis-major:
    restart: always
    image: ${CANISMAJOR_IMAGE:-quay.io/fiware/canis-major}
    hostname: canis-major
    depends_on:
      - ganache-cli
    expose:
      - "4000"
    environment:
      - MICRONAUT_SERVER_PORT=4000
      - MICRONAUT_HTTP_SERVICES_NGSI_URL=http://orion:1026
      - ETHEREUM_DLT_ADDRESS=http://ganache-cli:8545
      - GENERAL_NGSI_TENANT=orion
    networks:
      - default
    ports:
      - 4000:4000
