apiVersion: v1
kind: Pod
metadata:
  name: ganache-cli
spec:
  containers:
    - name: ganache-cli
      image: trufflesuite/ganache-cli:latest
      ports:
        - name: http
          containerPort: 8545
          hostPort: 8545