FORMAT: 1A
HOST: http://localhost:4000/

# Canis Major - Blockchain Adaptor(for PoweredBy 'FIWARE Architectures')

CanisMajor is a blockchain adaptor that supports various DLT, the adaptor aims to submit the data to DLT in Powered By FIWARE Architecture.

The adaptor will not be recommended to work for public-permissionless blockchains (specially tokens, cryptocurrencies).


## Version [/version]
### Get the Current Version [GET]
+ Response 200 (application/json)

        {
            "name": "canismajor",
            "version": "0.0.1"
        }
        
        
## Health [/health]
### Get the Health of Connected Node and Instances [GET]
+ Response 200 (application/json) 

        {
            "name": "implementation pending",
            "version": "implementation pending"
        }
        
## Group Configuration
Using Config APIs you can configure NGSI-V2 and NGSI-LD Payload to be submitted in DLTs (Currently support ETH Clients only). 

### /config{?offset,limit}
#### List All Configs [GET]
+ Parameters
    + offset (optional) - Pagination Count
    + limit (optional) - Number of records in one offset

+ Response 200 (application/json)

        {
            "offset": 0,
            "limit": 25,
            "count": 1,
            "records": [
                {
                    "id": 12,
                    "contextType": "AgriProductType",
                    "contextMapping": [
                        {
                            "set": [
                                "price"
                            ]
                        }
                    ],
                    "metadata": {
                        "abi": [
                            {
                                "name": "set",
                                "type": "function",
                                "inputs": [
                                    {
                                        "name": "x",
                                        "type": "uint256"
                                    }
                                ],
                                "outputs": [],
                                "payable": false,
                                "constant": false,
                                "stateMutability": "nonpayable"
                            }
                        ],
                        "contractAddress": "0xbfb86117e3f7a5f3975de30574d9e19384ab7078"
                    },
                    "createdAt": "2021-02-05T15:10:04.000Z",
                    "updatedAt": "2021-02-05T15:10:04.000Z"
                }
            ]
        }

### /config/{id}

#### Get A Config [GET]
+ Parameters
    + id - configId you want to fetch

+ Response 200 (application/json)

        {
            "offset": 0,
            "limit": 25,
            "count": 1,
            "records": [
                {
                    "id": 12,
                    "contextType": "AgriProductType",
                    "contextMapping": [
                        {
                            "set": [
                                "price"
                            ]
                        }
                    ],
                    "metadata": {
                        "abi": [
                            {
                                "name": "set",
                                "type": "function",
                                "inputs": [
                                    {
                                        "name": "x",
                                        "type": "uint256"
                                    }
                                ],
                                "outputs": [],
                                "payable": false,
                                "constant": false,
                                "stateMutability": "nonpayable"
                            }
                        ],
                        "contractAddress": "0xbfb86117e3f7a5f3975de30574d9e19384ab7078"
                    },
                    "createdAt": "2021-02-05T15:10:04.000Z",
                    "updatedAt": "2021-02-05T15:10:04.000Z"
                }
            ]
        }

### /config
#### Create a Config [POST]

+ Request (application/json)

        {
           "contextType":"AgriProductType",
           "contextMapping":[{
                 "set":[
                    "price"
                 ]
            }],
               "metadata": {
                    "contractAddress": "0xbfb86117e3f7a5f3975de30574d9e19384ab7078",
                    "abi":[
                        {
                            "name":"set",
                            "type":"function",
                            "inputs":[
                                {
                                "name":"x",
                                "type":"uint256"
                                }
                            ],
                            "outputs":[
                                
                            ],
                            "payable":false,
                            "constant":false,
                            "stateMutability":"nonpayable"
                        }
                    ]
               }
        }

+ Response 201 (application/json)

    + Body
    {
       "id":14,
       "contextType":"AgriProductType",
       "contextMapping":[
          {
             "set":[
                "price"
             ]
          }
       ],
       "metadata":{
          "contractAddress":"0xbfb86117e3f7a5f3975de30574d9e19384ab7078",
          "abi":[
             {
                "name":"set",
                "type":"function",
                "inputs":[
                   {
                      "name":"x",
                      "type":"uint256"
                   }
                ],
                "outputs":[
                   
                ],
                "payable":false,
                "constant":false,
                "stateMutability":"nonpayable"
             }
          ]
       },
       "updatedAt":"2021-02-17T13:33:11.935Z",
       "createdAt":"2021-02-17T13:33:11.935Z"
    }

+ Response 400 (application/json)

    + Body
    {
        "status": 400,
        "message": "config already exist"
    }
    
    
### /config
#### update a Config [PUT]

+ Request (application/json)

        {
           "contextType":"AgriProductType",
           "contextMapping":[{
                 "set":[
                    "price"
                 ]
            }],
               "metadata": {
                    "contractAddress": "0xbfb86117e3f7a5f3975de30574d9e19384ab7078",
                    "abi":[
                        {
                            "name":"set",
                            "type":"function",
                            "inputs":[
                                {
                                "name":"x",
                                "type":"uint256"
                                }
                            ],
                            "outputs":[
                                
                            ],
                            "payable":false,
                            "constant":false,
                            "stateMutability":"nonpayable"
                        }
                    ]
               }
        }

+ Response 200 (application/json)

    + Body
    {
       "id":14,
       "contextType":"AgriProductType",
       "contextMapping":[
          {
             "set":[
                "price"
             ]
          }
       ],
       "metadata":{
          "contractAddress":"0xbfb86117e3f7a5f3975de30574d9e19384ab7078",
          "abi":[
             {
                "name":"set",
                "type":"function",
                "inputs":[
                   {
                      "name":"x",
                      "type":"uint256"
                   }
                ],
                "outputs":[
                   
                ],
                "payable":false,
                "constant":false,
                "stateMutability":"nonpayable"
             }
          ]
       },
       "updatedAt":"2021-02-17T13:33:11.935Z",
       "createdAt":"2021-02-17T13:33:11.935Z"
    }

### /config/{id}

#### Delete A Config [DELETE]
+ Parameters
    + id - configId you want to fetch

+ Response 200 (application/json)

        {
            "success": true,
            "message": "deleted_successfully"
        }
        
+ Response 404 (application/json)

        {
            "status": 404,
            "message": "not_found"
        }


## Group Entities
Get the transacition recipt of the entities persisted in DLT.

### /entity{?offset,limit}
#### List All Entities [GET]
+ Parameters
    + offset (optional) - Pagination Count
    + limit (optional) - Number of records in one offset

+ Response 200 (application/json)

        {
            "offset": 0,
            "limit": 25,
            "count": 1,
            "records": [
                {
                    "id": 5,
                    "entityId": "urn:ngsi-ld:AgriProductType:398a3224-6a12-4531-9f84-e94o24411257",
                    "txDetails": [
                        {
                            "configId": 12,
                            "txRecipt": {
                                "to": "0xb17257f80b73535e69337ad0aa19b17a17118e51",
                                "from": "0xfd572dccb853ed7651b5988d8ac18c2b632b1b67",
                                "events": {},
                                "status": true,
                                "gasUsed": 22209,
                                "blockHash": "0xa3a258fb747442a896e5a42fe733fd9e167f794b323dfd67dad7575b14d86fc0",
                                "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                                "blockNumber": 4,
                                "contractAddress": null,
                                "transactionHash": "0xa1d0a8f5c0a1c2053b90e760e5477c10c4d6ef9e969c8df29eb860bd64ad3759",
                                "transactionIndex": 0,
                                "cumulativeGasUsed": 22209
                            }
                        }
                    ],
                    "createdAt": "2021-02-17T10:55:43.000Z",
                    "updatedAt": "2021-02-17T10:55:43.000Z"
                }
            ]
        }

### /entity/{id}

#### Get A Entity [GET]
+ Parameters
    + id - entityId you want to fetch

+ Response 200 (application/json)

        {
            "id": 5,
            "entityId": "urn:ngsi-ld:AgriProductType:398a3224-6a12-4531-9f84-e94o24411257",
            "txDetails": [
                {
                    "configId": 12,
                    "txRecipt": {
                        "to": "0xb17257f80b73535e69337ad0aa19b17a17118e51",
                        "from": "0xfd572dccb853ed7651b5988d8ac18c2b632b1b67",
                        "events": {},
                        "status": true,
                        "gasUsed": 22209,
                        "blockHash": "0xa3a258fb747442a896e5a42fe733fd9e167f794b323dfd67dad7575b14d86fc0",
                        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                        "blockNumber": 4,
                        "contractAddress": null,
                        "transactionHash": "0xa1d0a8f5c0a1c2053b90e760e5477c10c4d6ef9e969c8df29eb860bd64ad3759",
                        "transactionIndex": 0,
                        "cumulativeGasUsed": 22209
                    }
                }
            ],
            "createdAt": "2021-02-17T10:55:43.000Z",
            "updatedAt": "2021-02-17T10:55:43.000Z"
        }
        
        
#### Delete A Entity [DELETE]
+ Parameters
    + id - EntityId you want to fetch

+ Response 200 (application/json)

        {
            "success": true,
            "message": "deleted_successfully"
        }
        
+ Response 404 (application/json)

        {
            "status": 404,
            "message": "not_found"
        }        
        
        
### /notify
#### Context Broker Notify [POST]

The endpoint use to notify the Canis Major from the Context Broker.