name: generate API docs
on:
  push:
    branches:
      - hardening/doc
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
            fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - name: Install node package
          uses: npm install --global @redocly/cli
        - name: Generate API Doc
          run: redoc-cli build-docs ./api/api.yaml
