name: Integration-test

on:
  push

jobs:
  it:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        storagetype: ["iota", "ipfs","merkle"]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '17'
        java-package: jdk

    - name: Build CanisMajor
      id: canis-major-build
      run: docker build . -t canis-major

    - name: Run compose
      id: compose
      env:
        CANISMAJOR_IMAGE: canis-major
      run: |
        cd it/docker-compose
        docker-compose -f docker-compose-env.yaml -f docker-compose-${{ matrix.storagetype }}.yaml up -d
        
    - name: Extract Branch Name
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

    - name: Run tests
      id: test
      if: env.BRANCH == 'master'
      run: |
        cd it/
        mvn clean install -Dstoragetype=${{ matrix.storagetype }} -Dcucumber.publish-token=${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

    - name: Run tests
      id: test-dev
      if: env.BRANCH != 'master'
      run: |
        cd it/
        mvn clean install -Dstoragetype=${{ matrix.storagetype }} -Dcucumber.publish-token=${{ secrets.CUCUMBER_PUBLISH_TOKEN_DEV }}

    - name: Collect logs
      if: ${{ failure() }}
      run: |
        cd it/docker-compose
        docker-compose -f docker-compose-env.yaml -f docker-compose-${{ matrix.storagetype }}.yaml logs