name: Integration-test

on:
  push

jobs:
  it:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '17'
        java-package: jdk

    - name: Build Vault
      id: vault-build
      run: |
        docker build -f ./it/vault/Dockerfile ./it/vault -t vault-ethereum

    - name: Build CanisMajor
      id: canis-major-build
      run: |
        mvn clean install jib:dockerBuild -DskipTests -Pdocker -Dimage.repository="fiware"

    - name: Run compose
      id: compose
      env:
        CANISMAJOR_IMAGE: quay.io/fiware/canis-major
        VAULT_IMAGE: vault-ethereum
      run: |
        cd it/docker-compose
        docker-compose -f docker-compose-env.yaml -f docker-compose-java.yaml up -d
        
    - name: Extract Branch Name
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

    - name: Run tests
      id: test
      if: env.BRANCH == 'master'
      run: |
        cd it/
        mvn clean install -Dcucumber.publish-token=${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

    - name: Run tests
      id: test-dev
      if: env.BRANCH != 'master'
      run: |
        cd it/
        mvn clean install -Dcucumber.publish-token=${{ secrets.CUCUMBER_PUBLISH_TOKEN_DEV }}

    - name: Collect logs
      if: ${{ failure() }}
      run: |
        cd it/docker-compose
        docker-compose -f docker-compose-env.yaml -f docker-compose-${{ matrix.storagetype }}.yaml logs